apiVersion: v1
kind: ConfigMap

metadata:
  name: skip-crds-plugin-config

data:
  skip-crds-plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: skip-crds-plugin
    spec:
      generate:
        command: ["/bin/sh", "-c"]
        args:
          - kustomize build --enable-helm | plugin-skip-crds
